spring.application.name=springboot2026
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


jwt.secret=NjRieXRlc1NlY3JldEtleUZvckpXVEhTMjU2U2lnbmF0dXJlVGhpc0lzVmVyeVNlY3VyZUtleUZvclNwcmluZ0Jvb3RBcHBsaWNhdGlvbjIwMjY=
jwt.expiration=3600000